name: Build and Push Docker Image to Docker Hub

on:
  push:
  schedule:
    - cron: "0 0 * * 1" # Update every Monday at 00:00
  
jobs:
  push_to_dockerhub:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Make script executable
        run: chmod +x ./getVersions.sh

      - name: Get versions of modules
        id: version
        run: |
          ./getVersions.sh
          echo "{DOCKER_TAG}=test" >> "$GITHUB_OUTPUT"
          echo "{NGINX_VERSION}={$nginx_version}" >> "$GITHUB_OUTPUT"
          echo "{RTMP_MODULE_VERSION}={$rtmp_module_commit_hash}" >> "$GITHUB_OUTPUT"

      - name: build and push image to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}:latest
            ${{secrets.DOCKERHUB_USERNAME}}:${{ steps.version.outputs.DOCKER_TAG }}
          build-args: |
            NGINX_VERSION=${{ steps.version.outputs.NGINX_VERSION }}
            RTMP_MODULE_VERSION=${{ steps.version.outputs.RTMP_MODULE_VERSION }}
    
